limit_req_zone $binary_remote_addr zone=api:10m rate=10r/s;

server {
    listen 80;
    server_name localhost;

    # Host the frontend files
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
    }

    # Reverse proxy API calls to the backend service
    location /api/ {
        limit_req zone=api burst=20 nodelay;
        limit_req_status 429;

        proxy_pass         http://backend:8080/api/;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }

}
