server {
    listen 80;
    server_name localhost;

    # Host the frontend files
    location / {
        root   /usr/share/nginx/html;
        index  index.html;
    }

    # Reverse proxy API calls to the backend service
    location /api/ {
        proxy_pass         http://backend:8080/api/;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
    }

}
