services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_started

  tests:
    image: eclipse-temurin:25-jdk
    container_name: backend-tests
    working_dir: /app/backend
    volumes:
      - .:/app
      - maven-cache:/root/.m2
    command: ./mvnw test
    profiles:
      - tests

volumes:
  maven-cache:
